services:
  - type: web
    name: Ava
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ava.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: ava.settings
