services:
  - type: web
    name: myapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT asgi:application
envVars:
  - key: DJANGO_SECRET_KEY
    generateValue: true
  - key: DJANGO_SETTINGS_MODULE
    value: settings
