# Generated by Django 5.1.7 on 2025-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('chill', 'Chill'), ('party', 'Party Animal'), ('homebody', 'Homebody')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('serious', 'Serious'), ('marriage', 'Marriage')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='want_kids',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10),
        ),
    ]
