# Generated by Django 5.1.7 on 2025-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_hobbies_profile_lifestyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
