# Generated by Django 5.1.7 on 2025-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='gallery_images/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
